//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowndesProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOM_Nomination
    {
        public int Id { get; set; }
        public bool Nomination_Type { get; set; }
        public string Nominator_Employee_Number { get; set; }
        public string Nominator_Employee_Full_Name { get; set; }
        public string Nomination_Reason { get; set; }
        public string Nominee_Employee_Number { get; set; }
        public string Nominee_Emp_or_Team_Name { get; set; }
        public Nullable<System.DateTime> Submission_Date { get; set; }
    }
}
