//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowndesProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UltiPro
    {
        public int Id { get; set; }
        public string employment_status { get; set; }
        public string employee_number { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string preferred_first_name { get; set; }
        public Nullable<System.DateTime> last_hire_date { get; set; }
        public string org_level_1 { get; set; }
        public string org_level_2 { get; set; }
        public string org_level_3 { get; set; }
        public string location_code { get; set; }
        public string gender_code { get; set; }
        public string job { get; set; }
        public string supervisor_name_last_suffix_first_mi { get; set; }
        public string supervisor_employee_number { get; set; }
        public string eecudfield01 { get; set; }
        public string work_extension { get; set; }
        public Nullable<System.DateTime> seniority { get; set; }
        public string work_phone { get; set; }
    }
}
